export type WallKind = "image" | "video" | "music" | "voice";
export type UseCase = "ad" | "ugc" | "show" | "film";

export type WallItem = {
  id: string;
  kind: WallKind;
  useCase: UseCase;
  model: string;
  prompt: string;
  modelSlug: string;
  image: string;
  video?: string;
  audioSrc?: string;
  audio?: { title: string; duration: string };
  span?: "sm" | "md" | "lg";
};

/**
 * Real showcase URLs sourced from official model pages (fal.ai galleries,
 * Google/OpenAI examples). Each URL is a public CDN link — no auth required.
 */
const R = {
  // ── Images ──
  seedream5pro_a:
    "https://v3b.fal.media/files/b/0aa16df4/ktjX_-2KKAw7bCTQgopGV_5b49dc459dfe484fbb1218fce0e24bc7.png",
  seedream5pro_b:
    "https://v3b.fal.media/files/b/0a94814a/vKQfFX-pXcXv4MDvgtybu_d79aaa7e8534459281ac0bb474872f4b.jpg",
  seedream5pro_c:
    "https://v3b.fal.media/files/b/0a94816f/BhHA2kmKyAQ8vJxw_HPQ4_2b4b35f0fbb0449195d84178ba988112.jpg",
  seedream5lite_a:
    "https://refinery.fal.media/url/https%3A%2F%2Fv3b.fal.media%2Ffiles%2Fb%2F0aa17b8e%2Fi_MTG_woBCy2l6WUU1LUh_bb01e1ba69ef40ec9d855741eaacd392.png/tr:w-1024,q-80/i_MTG_woBCy2l6WUU1LUh_bb01e1ba69ef40ec9d855741eaacd392.webp",
  seedream5lite_b:
    "https://v3b.fal.media/files/b/0a948152/0UucVYSOBXiyibwSyN3HT_38400743f04344a5b25b1cd9b551a625.jpg",
  nanobanana2_a:
    "https://storage.googleapis.com/falserverless/example_outputs/nano-banana-2-t2i-output.png",
  nanobanana2_b:
    "https://v3b.fal.media/files/b/0a948161/E43snBsqtEWRB2KGM6723_8b2971637e504a00b4bcf2cec7d544b6.jpg",
  nanobanana2lite:
    "https://v3b.fal.media/files/b/panda/-oMlZo9Yyj_Nzoza_tgds_GmLF86r5bOt50eMMKCszy_eacc949b3933443c9915a83c98fbe85e.png",
  gptimage2_a: "https://images.ctfassets.net/kftzwdyauwt9/I1fZJDVIImc76rO9pBrFj/3f941d5b06447057164bb08c2ae0b94a/ChatGPT_Image_Apr_14__2026__09_42_30_PM.png?w=1920&q=90&fm=webp",
  gptimage2_b:
    "https://v3b.fal.media/files/b/0a9486b9/Iti-a7lTmHZW6KlSZ80rU_output_1.png",
  qwenimage_a: "https://v3.fal.media/files/rabbit/KoIbq6nhDBDPxDQrivW-m.png",
  qwenimage_b:
    "https://v3b.fal.media/files/b/0a8f0995/slF9l2eNL_YSD7SqU7tUz_i35fsR92.jpg",
  wan27image_a:
    "https://v3b.fal.media/files/b/0a9413bb/qH6QY4JRzWxHOFKtCe70S_uPDJyzKZ.png",
  wan27imagepro:
    "https://v3.fal.media/files/elephant/rkH-9qoXtXu3rAYTsx9V5_image.webp",
  wan27image_poster:
    "https://v3.fal.media/files/lion/_I_io6Gtk83c72d-afXf8_image.webp",

  // ── Videos ──
  kling3pro_a: "https://v3b.fal.media/files/b/0a9270c0/M0OE5-o3n7Pj85CWWpGt2_output.mp4",
  kling3pro_b: "https://v3.fal.media/files/rabbit/YuUWKFq508zzWIiQ0i2vt_output.mp4",
  kling3pro_c: "https://v3.fal.media/files/koala/17e3xh08J4_PkHS_0cbwF_output.mp4",
  kling3turbo_a: "https://v3b.fal.media/files/b/0a9ea5e6/Z1gmj2xGCP-wyxUr7WheI_output.mp4",
  kling3turbo_b: "https://v3.fal.media/files/rabbit/Y5I8-7u3e7ogVSvPin1TS_output.mp4",
  kling3standard: "https://v3.fal.media/files/koala/VvGXP5xEhTR9ovGjpulJ7_output.mp4",
  kling34k: "https://v3.fal.media/files/lion/0wTlhR7GCXFI-_BZXGy99_output.mp4",
  kling3motion: "https://v3.fal.media/files/rabbit/5fu6OSZdvV825r2s_c0S8_output.mp4",
  seedance2fast: "https://v3b.fal.media/files/b/0a9f7ecf/jQvhuOlh8iQrO38GC4K_0_video.mp4",
  seedance2mini: "https://v3.fal.media/files/penguin/twy6u1yv09NvqsX0mMFM2_output.mp4",
  wan27video_a: "https://v3b.fal.media/files/b/0a940a49/fBFxYrVooHj29QIff8clR_xVVvbIQ0.mp4",
  wan27video_b: "https://v3b.fal.media/files/b/0a940a70/s4jC3lmmbU8Q6xM-SFtWB_m5JJudvy.mp4",
  wan27video_c:
    "https://v3b.fal.media/files/b/panda/a6SvJg96V8eoglMlYFShU_5385885-hd_1080_1920_25fps.mp4",
  happyhorse: "https://v3b.fal.media/files/b/0a9f39fd/N9U9ZDVOZvX13yQTzx0wN_NrDUbOAF.mp4",
  grokvideo: "https://v3b.fal.media/files/b/0a9c66a1/xx79_pXtz3hq4TByzo4Xc_jN5I675M.mp4",
  geminiomni: "https://v3b.fal.media/files/b/0a8f0997/JuDW2xl0mr6sJ_Kjz3Vxe_vidoeook.mp4",
  omnihuman: "https://v3b.fal.media/files/b/0a8f2447/EjMyhbOyYfxL8tDM9T59K_wan_animate_output.mp4",
  volclipsync:
    "https://v3b.fal.media/files/b/elephant/9Ofgiju3Peb3b5hriTuBH_wan_animate_output.mp4",
  dubbedvideo: "https://v3.fal.media/files/monkey/O-ekVTtYqeDblD1oSf2uv_dubbed_video.mp4",
  extraclip: "https://v3.fal.media/files/panda/f7tXRCjvwEcVlmxHuw8kO_2c7ab2540af44eceaf5ffde4e8d094ed.mp4",
  extraclip2: "https://v3.fal.media/files/lion/Fbuh3lO_HMT-pS0DATbio_tmp08c3v477.mp4",
  extraclip3: "https://v3b.fal.media/files/b/monkey/xjJYzO0jqMi7MxufJe5tx_wan_animate_output.mp4",
  extraclip4: "https://v3.fal.media/files/penguin/ln3x7H1p1jL0Pwo7675NI_output.mp4",
};

export const WALL_ITEMS: WallItem[] = [
  // ══════════════════ IMAGES ══════════════════
  {
    id: "i-seedream5pro-1",
    kind: "image",
    useCase: "ad",
    model: "Seedream 5.0 Pro",
    modelSlug: "seedream-5-pro",
    prompt:
      "Vibrant editorial of a model in contemporary fashion fused with West African textile patterns, Campbell Addy aesthetic, saturated palette.",
    image: R.seedream5pro_a,
    span: "lg",
  },
  {
    id: "i-seedream5pro-2",
    kind: "image",
    useCase: "show",
    model: "Seedream 5.0 Pro",
    modelSlug: "seedream-5-pro",
    prompt: "Portrait studio d'un chef pâtissier, lumière rembrandt, fond noir profond, éditorial.",
    image: R.seedream5pro_b,
    span: "md",
  },
  {
    id: "i-seedream5pro-3",
    kind: "image",
    useCase: "film",
    model: "Seedream 5.0 Pro",
    modelSlug: "seedream-5-pro",
    prompt: "Ruelle pavée de Lisbonne la nuit, lampadaires jaunes, silhouette solitaire.",
    image: R.seedream5pro_c,
    span: "sm",
  },
  {
    id: "i-seedream5lite-1",
    kind: "image",
    useCase: "ugc",
    model: "Seedream 5.0 Lite",
    modelSlug: "seedream-5-lite",
    prompt: "Realistic DSLR photograph of anthropomorphic dog enjoying ramen on the Great Wall of China.",
    image: R.seedream5lite_a,
    span: "md",
  },
  {
    id: "i-seedream5lite-2",
    kind: "image",
    useCase: "ad",
    model: "Seedream 5.0 Lite",
    modelSlug: "seedream-5-lite",
    prompt: "Flat lay accessoires cuir camel sur fond crème, lumière rasante, ombres nettes.",
    image: R.seedream5lite_b,
    span: "sm",
  },
  {
    id: "i-nanobanana2-1",
    kind: "image",
    useCase: "ad",
    model: "Nano Banana 2",
    modelSlug: "nano-banana-2",
    prompt: "Action shot of a black lab swimming in a suburban pool, water-level split view.",
    image: R.nanobanana2_a,
    span: "md",
  },
  {
    id: "i-nanobanana2-2",
    kind: "image",
    useCase: "show",
    model: "Nano Banana 2",
    modelSlug: "nano-banana-2",
    prompt: "Décor de plateau TV cuisine ouverte, tons chauds bois et cuivre, projecteurs allumés.",
    image: R.nanobanana2_b,
    span: "sm",
  },
  {
    id: "i-nanobanana2lite-1",
    kind: "image",
    useCase: "ugc",
    model: "Nano Banana 2 Lite",
    modelSlug: "nano-banana-2-lite",
    prompt: "Product hero d'un tube de crème hydratante, fond pastel, ombres douces, style e-commerce.",
    image: R.nanobanana2lite,
    span: "sm",
  },
  {
    id: "i-gptimage2-1",
    kind: "image",
    useCase: "film",
    model: "GPT Image 2",
    modelSlug: "gpt-image-2",
    prompt:
      "The portraits are taken outdoors, indoors, in specific, intimate, suburban settings. Maintain photographic style and realism, shots taken using view cameras with colour film and medium-format cameras, pushing the strangeness of subjects and locations further. Kitsch and middle classes, yet with elements that could not exist in reality, either aesthetically or physically.",
    image: R.gptimage2_a,
    span: "lg",
  },
  {
    id: "i-gptimage2-2",
    kind: "image",
    useCase: "ugc",
    model: "GPT Image 2",
    modelSlug: "gpt-image-2",
    prompt: "Écran d'iPhone posé sur un carnet, message d'inscription à une newsletter mode.",
    image: R.gptimage2_b,
    span: "sm",
  },
  {
    id: "i-qwen-1",
    kind: "image",
    useCase: "ad",
    model: "Qwen Image 2.0",
    modelSlug: "qwen-image-20",
    prompt: "Mount Fuji with cherry blossoms in the foreground, clear sky, peaceful spring day.",
    image: R.qwenimage_a,
    span: "md",
  },
  {
    id: "i-qwen-2",
    kind: "image",
    useCase: "ugc",
    model: "Qwen Image 2.0",
    modelSlug: "qwen-image-20",
    prompt: "Plante monstera dans un intérieur chaleureux, lumière du soir dorée, style lifestyle.",
    image: R.qwenimage_b,
    span: "sm",
  },
  {
    id: "i-wan27image-1",
    kind: "image",
    useCase: "show",
    model: "Wan 2.7 Image",
    modelSlug: "wan-27-image",
    prompt: "Titre d'émission « Nuits de Dakar » en typographie art déco dorée sur fond noir texturé.",
    image: R.wan27image_a,
    span: "md",
  },
  {
    id: "i-wan27image-2",
    kind: "image",
    useCase: "film",
    model: "Wan 2.7 Image",
    modelSlug: "wan-27-image",
    prompt: "Portrait cinématographique d'une comédienne, cheveux au vent, tempête à l'horizon.",
    image: R.wan27image_poster,
    span: "sm",
  },
  {
    id: "i-wan27imagepro-1",
    kind: "image",
    useCase: "ad",
    model: "Wan 2.7 Image Pro",
    modelSlug: "wan-27-image-pro",
    prompt: "Flacon de parfum ambré sur marbre travertin, lumière rasante d'aube, contre-jour doux.",
    image: R.wan27imagepro,
    span: "md",
  },

  // ══════════════════ VIDEOS ══════════════════
  {
    id: "v-kling3pro-1",
    kind: "video",
    useCase: "ugc",
    model: "Kling 3.0",
    modelSlug: "kling-3",
    prompt:
      "Slow cinematic push-in through an empty ancient temple, fog drifts, golden light catches dust particles.",
    image: R.kling3pro_a,
    video: R.kling3pro_a,
    span: "md",
  },
  {
    id: "v-kling3pro-2",
    kind: "video",
    useCase: "film",
    model: "Kling 3.0",
    modelSlug: "kling-3",
    prompt: "Sweeping aerial shot over misty mountains at sunrise, clouds rolling through valleys.",
    image: R.kling3pro_b,
    video: R.kling3pro_b,
    span: "lg",
  },
  {
    id: "v-kling3pro-3",
    kind: "video",
    useCase: "ad",
    model: "Kling 3.0",
    modelSlug: "kling-3",
    prompt: "Ultra slow-motion of ink dropping into clear water, blooming tendrils, macro cinematic.",
    image: R.kling3pro_c,
    video: R.kling3pro_c,
    span: "md",
  },
  {
    id: "v-kling3turbo-1",
    kind: "video",
    useCase: "ad",
    model: "Kling 3.0 Turbo",
    modelSlug: "kling-3-turbo",
    prompt:
      "Lion cubs paw and tumble against the lioness, she lifts her head and licks one. Photorealistic, tender.",
    image: R.kling3turbo_a,
    video: R.kling3turbo_a,
    span: "md",
  },
  {
    id: "v-kling3turbo-2",
    kind: "video",
    useCase: "ugc",
    model: "Kling 3.0 Turbo",
    modelSlug: "kling-3-turbo",
    prompt: "Café qui coule d'une machine expresso au ralenti, gouttes en macro, vapeur.",
    image: R.kling3turbo_b,
    video: R.kling3turbo_b,
    span: "sm",
  },
  {
    id: "v-kling3standard-1",
    kind: "video",
    useCase: "show",
    model: "Kling 3.0 Standard",
    modelSlug: "kling-3-standard",
    prompt: "Chef découpe un ananas dans un studio cuisine, plan macro, mouvement de dolly lent.",
    image: R.kling3standard,
    video: R.kling3standard,
    span: "md",
  },
  {
    id: "v-kling34k-1",
    kind: "video",
    useCase: "film",
    model: "Kling 3.0 4K",
    modelSlug: "kling-3-4k",
    prompt: "Plan aérien d'un désert au coucher du soleil, dunes ondulantes, mouvement de caméra lent.",
    image: R.kling34k,
    video: R.kling34k,
    span: "lg",
  },
  {
    id: "v-kling3motion-1",
    kind: "video",
    useCase: "ugc",
    model: "Kling 3.0 Motion",
    modelSlug: "kling-3-motion",
    prompt: "Yoga au bord d'une piscine à Bali, salutation au soleil, plan large, lumière chaude.",
    image: R.kling3motion,
    video: R.kling3motion,
    span: "md",
  },
  {
    id: "v-seedance2fast-1",
    kind: "video",
    useCase: "ad",
    model: "Seedance 2.0 Fast",
    modelSlug: "seedance-2-fast",
    prompt:
      "Ultra-detailed 4K macro of a Bengal tiger resting in golden morning light, slow rack focus.",
    image: R.seedance2fast,
    video: R.seedance2fast,
    span: "md",
  },
  {
    id: "v-seedance2mini-1",
    kind: "video",
    useCase: "ugc",
    model: "Seedance 2.0 Mini",
    modelSlug: "seedance-2-mini",
    prompt: "Créatrice UGC déballe une paire de sneakers en unboxing, plan serré, lumière naturelle.",
    image: R.seedance2mini,
    video: R.seedance2mini,
    span: "sm",
  },
  {
    id: "v-wan27video-1",
    kind: "video",
    useCase: "film",
    model: "Wan 2.7 Video",
    modelSlug: "wan-27-video",
    prompt: "Extreme close-up of dark chocolate poured over a layered cake, glossy sheen, cocoa dust.",
    image: R.wan27video_a,
    video: R.wan27video_a,
    span: "lg",
  },
  {
    id: "v-wan27video-2",
    kind: "video",
    useCase: "ad",
    model: "Wan 2.7 Video",
    modelSlug: "wan-27-video",
    prompt: "Voiture électrique traverse une ville de nuit sous la pluie, reflets néons, travelling.",
    image: R.wan27video_b,
    video: R.wan27video_b,
    span: "md",
  },
  {
    id: "v-wan27video-3",
    kind: "video",
    useCase: "ugc",
    model: "Wan 2.7 Video",
    modelSlug: "wan-27-video",
    prompt: "Reel vertical d'une danseuse dans un studio blanc, mouvement fluide, plan portrait.",
    image: R.wan27video_c,
    video: R.wan27video_c,
    span: "sm",
  },
  {
    id: "v-happyhorse-1",
    kind: "video",
    useCase: "show",
    model: "HappyHorse 1.1",
    modelSlug: "happyhorse-11",
    prompt:
      "Character in a cozy dim room strums a guitar and says: 'This next one I wrote at three in the morning.'",
    image: R.happyhorse,
    video: R.happyhorse,
    span: "md",
  },
  {
    id: "v-grok-1",
    kind: "video",
    useCase: "ugc",
    model: "Grok Video 1.5",
    modelSlug: "grok-video-15",
    prompt: "Medium shot, elle parle chaleureusement en présentant un produit, push-in cinématique.",
    image: R.grokvideo,
    video: R.grokvideo,
    span: "md",
  },
  {
    id: "v-geminiomni-1",
    kind: "video",
    useCase: "show",
    model: "Gemini Omni Video",
    modelSlug: "gemini-omni-video",
    prompt: "Présentateur télé annonce le titre du jour, plan taille, décor d'info moderne.",
    image: R.geminiomni,
    video: R.geminiomni,
    span: "md",
  },
  {
    id: "v-omnihuman-1",
    kind: "video",
    useCase: "ad",
    model: "OmniHuman 1.5",
    modelSlug: "omnihuman-15",
    prompt: "Avatar photoréaliste parle face caméra, lip-sync parfait, éclairage studio.",
    image: R.omnihuman,
    video: R.omnihuman,
    span: "md",
  },
  {
    id: "v-volclipsync-1",
    kind: "video",
    useCase: "ugc",
    model: "Volcengine Lip Sync",
    modelSlug: "volcengine-lip-sync",
    prompt: "Interview d'un créateur relookée avec lip-sync multilingue, plan poitrine.",
    image: R.volclipsync,
    video: R.volclipsync,
    span: "sm",
  },
  {
    id: "v-extra-1",
    kind: "video",
    useCase: "film",
    model: "Kling 3.0",
    modelSlug: "kling-3",
    prompt: "Doublage cinématographique d'un dialogue de film noir, ambiance jazz smoky bar.",
    image: R.dubbedvideo,
    video: R.dubbedvideo,
    span: "md",
  },
  {
    id: "v-extra-2",
    kind: "video",
    useCase: "ad",
    model: "Seedance 2.0 Fast",
    modelSlug: "seedance-2-fast",
    prompt: "Sneaker qui tourne en lévitation sur fond dégradé, éclairage studio, style pub premium.",
    image: R.extraclip,
    video: R.extraclip,
    span: "sm",
  },
  {
    id: "v-extra-3",
    kind: "video",
    useCase: "show",
    model: "Wan 2.7 Video",
    modelSlug: "wan-27-video",
    prompt: "Générique d'émission culinaire, ingrédients en lévitation autour d'un logo doré.",
    image: R.extraclip2,
    video: R.extraclip2,
    span: "md",
  },
  {
    id: "v-extra-4",
    kind: "video",
    useCase: "ugc",
    model: "OmniHuman 1.5",
    modelSlug: "omnihuman-15",
    prompt: "Créateur qui présente une routine matinale, plan face, ambiance chaleureuse.",
    image: R.extraclip3,
    video: R.extraclip3,
    span: "sm",
  },
  {
    id: "v-extra-5",
    kind: "video",
    useCase: "film",
    model: "Kling 3.0 4K",
    modelSlug: "kling-3-4k",
    prompt: "Plan drone au-dessus d'une forêt boréale, brume matinale, lumière filtrée.",
    image: R.extraclip4,
    video: R.extraclip4,
    span: "md",
  },

  // ══════════════════ VOICE ══════════════════
  {
    id: "a-voice-1",
    kind: "voice",
    useCase: "film",
    model: "ElevenLabs V3",
    modelSlug: "eleven-v3",
    prompt: "Voix off française, grave et calme, teaser d'une mini-série policière.",
    image: R.seedream5pro_c,
    audio: { title: "Teaser — Voix off FR", duration: "0:18" },
    span: "sm",
  },
  {
    id: "a-voice-2",
    kind: "voice",
    useCase: "ad",
    model: "ElevenLabs V3",
    modelSlug: "eleven-v3",
    prompt: "Voix off portugaise énergique pour spot radio, ton chaleureux et rythmé.",
    image: R.seedream5pro_b,
    audio: { title: "Spot radio — PT-BR", duration: "0:22" },
    span: "sm",
  },

  // ══════════════════ MUSIC ══════════════════
  {
    id: "a-music-1",
    kind: "music",
    useCase: "show",
    model: "ElevenLabs Music",
    modelSlug: "eleven-v3",
    prompt: "Afrobeat talk-show intro, kora + warm synths, 90 BPM, optimistic mood.",
    image: R.seedream5pro_a,
    audio: { title: "Afrobeat Intro — Studio Lomé", duration: "0:42" },
    span: "sm",
  },
];
