/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppPreviewRouteImport } from './routes/app-preview'
import { Route as AppRouteImport } from './routes/app'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CanvasIndexRouteImport } from './routes/canvas/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as AuthPathnameRouteImport } from './routes/auth.$pathname'
import { Route as AppModelsRouteImport } from './routes/app.models'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppDevelopersRouteImport } from './routes/app.developers'
import { Route as AppAccountRouteImport } from './routes/app.account'
import { Route as AccountPathnameRouteImport } from './routes/account.$pathname'
import { Route as AppModelsSlugRouteImport } from './routes/app.models.$slug'

const AppPreviewRoute = AppPreviewRouteImport.update({
  id: '/app-preview',
  path: '/app-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasIndexRoute = CanvasIndexRouteImport.update({
  id: '/canvas/',
  path: '/canvas/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppDevelopersRoute = AppDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AccountPathnameRoute = AccountPathnameRouteImport.update({
  id: '/account/$pathname',
  path: '/account/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const AppModelsSlugRoute = AppModelsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppModelsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/app': typeof AppRouteWithChildren
  '/app-preview': typeof AppPreviewRoute
  '/account/$pathname': typeof AccountPathnameRoute
  '/app/account': typeof AppAccountRoute
  '/app/developers': typeof AppDevelopersRoute
  '/app/history': typeof AppHistoryRoute
  '/app/models': typeof AppModelsRouteWithChildren
  '/auth/$pathname': typeof AuthPathnameRoute
  '/r/$code': typeof RCodeRoute
  '/app/': typeof AppIndexRoute
  '/canvas/': typeof CanvasIndexRoute
  '/app/models/$slug': typeof AppModelsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/app-preview': typeof AppPreviewRoute
  '/account/$pathname': typeof AccountPathnameRoute
  '/app/account': typeof AppAccountRoute
  '/app/developers': typeof AppDevelopersRoute
  '/app/history': typeof AppHistoryRoute
  '/app/models': typeof AppModelsRouteWithChildren
  '/auth/$pathname': typeof AuthPathnameRoute
  '/r/$code': typeof RCodeRoute
  '/app': typeof AppIndexRoute
  '/canvas': typeof CanvasIndexRoute
  '/app/models/$slug': typeof AppModelsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-denied': typeof AccessDeniedRoute
  '/app': typeof AppRouteWithChildren
  '/app-preview': typeof AppPreviewRoute
  '/account/$pathname': typeof AccountPathnameRoute
  '/app/account': typeof AppAccountRoute
  '/app/developers': typeof AppDevelopersRoute
  '/app/history': typeof AppHistoryRoute
  '/app/models': typeof AppModelsRouteWithChildren
  '/auth/$pathname': typeof AuthPathnameRoute
  '/r/$code': typeof RCodeRoute
  '/app/': typeof AppIndexRoute
  '/canvas/': typeof CanvasIndexRoute
  '/app/models/$slug': typeof AppModelsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-denied'
    | '/app'
    | '/app-preview'
    | '/account/$pathname'
    | '/app/account'
    | '/app/developers'
    | '/app/history'
    | '/app/models'
    | '/auth/$pathname'
    | '/r/$code'
    | '/app/'
    | '/canvas/'
    | '/app/models/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-denied'
    | '/app-preview'
    | '/account/$pathname'
    | '/app/account'
    | '/app/developers'
    | '/app/history'
    | '/app/models'
    | '/auth/$pathname'
    | '/r/$code'
    | '/app'
    | '/canvas'
    | '/app/models/$slug'
  id:
    | '__root__'
    | '/'
    | '/access-denied'
    | '/app'
    | '/app-preview'
    | '/account/$pathname'
    | '/app/account'
    | '/app/developers'
    | '/app/history'
    | '/app/models'
    | '/auth/$pathname'
    | '/r/$code'
    | '/app/'
    | '/canvas/'
    | '/app/models/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AppRoute: typeof AppRouteWithChildren
  AppPreviewRoute: typeof AppPreviewRoute
  AccountPathnameRoute: typeof AccountPathnameRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
  RCodeRoute: typeof RCodeRoute
  CanvasIndexRoute: typeof CanvasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app-preview': {
      id: '/app-preview'
      path: '/app-preview'
      fullPath: '/app-preview'
      preLoaderRoute: typeof AppPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/': {
      id: '/canvas/'
      path: '/canvas'
      fullPath: '/canvas/'
      preLoaderRoute: typeof CanvasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/models': {
      id: '/app/models'
      path: '/models'
      fullPath: '/app/models'
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/developers': {
      id: '/app/developers'
      path: '/developers'
      fullPath: '/app/developers'
      preLoaderRoute: typeof AppDevelopersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/account/$pathname': {
      id: '/account/$pathname'
      path: '/account/$pathname'
      fullPath: '/account/$pathname'
      preLoaderRoute: typeof AccountPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/models/$slug': {
      id: '/app/models/$slug'
      path: '/$slug'
      fullPath: '/app/models/$slug'
      preLoaderRoute: typeof AppModelsSlugRouteImport
      parentRoute: typeof AppModelsRoute
    }
  }
}

interface AppModelsRouteChildren {
  AppModelsSlugRoute: typeof AppModelsSlugRoute
}

const AppModelsRouteChildren: AppModelsRouteChildren = {
  AppModelsSlugRoute: AppModelsSlugRoute,
}

const AppModelsRouteWithChildren = AppModelsRoute._addFileChildren(
  AppModelsRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppDevelopersRoute: typeof AppDevelopersRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppModelsRoute: typeof AppModelsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppDevelopersRoute: AppDevelopersRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppModelsRoute: AppModelsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AppRoute: AppRouteWithChildren,
  AppPreviewRoute: AppPreviewRoute,
  AccountPathnameRoute: AccountPathnameRoute,
  AuthPathnameRoute: AuthPathnameRoute,
  RCodeRoute: RCodeRoute,
  CanvasIndexRoute: CanvasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
